### ISSUE TITLE
About Auto-Scraping

### ISSUE THREAD

**Issue by colinhd8** [chros73/rtorrent-ps_setup#104]
There's a config about auto-scraping in the file of rtorrent.rc like this:
```ini
# Regularly update scrape information for all torrents (even stopped ones), it won't affect the operation of rtorrent, but nice to have these values updated.
# This info is only updated when rtorrent starts or a torrent is added by default.
# Try to balance calls to not fire them up at the same time (since multiscraping isn't implemented in libtorrent). Check for update every 5 minutes and distinguish between 2 groups:
#  - transferring (uploading and/or downloading) torrents: update in every 10 minutes
#   - non-transferring torrents: update in every 12 hours
# helper method: sets current time in a custom field (tm_last_scrape) and saves session
method.insert = d.last_scrape.set, simple|private, "d.custom.set=tm_last_scrape,$cat=$system.time=; d.save_full_session="
# helper method: sends the scrape request and sets the tm_last_scrape timestamp and saves session
method.insert = d.last_scrape.send_set, simple, "d.tracker.send_scrape=0;d.last_scrape.set="
# helper method: decides whether the required time interval (with the help of an argument) has passed and if so calls the above method
method.insert = d.last_scrape.check_elapsed, simple|private, "branch={(elapsed.greater,$d.custom=tm_last_scrape,$argument.0=),d.last_scrape.send_set=}"
# helper method: checks for non-existing/empty custom field to be able to test its validity later
method.insert = d.last_scrape.check, simple|private, "branch={d.custom=tm_last_scrape,d.last_scrape.check_elapsed=$argument.0=,d.last_scrape.send_set=}"
# sets custom field (tm_last_scrape) to current time only for torrents just has been added (skips setting time on purpose when rtorrent started)
method.set_key = event.download.inserted_new, last_scrape_i, "d.last_scrape.set="
# check for update every 5 minutes (300 sec) and update scrape info for transferring torrents in every 10 minutes (600-20=580 sec) and for non-transferring ones in every 12 hours (43200-20=43180 sec)
schedule2 = last_scrape_t, 300, 300, "d.multicall2=main,\"branch=\\\"or={d.up.rate=,d.down.rate=}\\\",d.last_scrape.check=580,d.last_scrape.check=43180\""
```

I want to know what's the difference between it and announcement requesting. 
and what does it good for.

Thank you.

**Comment by chros73** [comment]
You can include config snippet inside 3 backslashes :)

See the Intro part of the corresponding [wiki page](https://github.com/chros73/rtorrent-ps_setup/wiki/Auto-Scraping#introduction) for more info.

**Comment by chros73** [comment]
And if you want to use it don't forget to take a look at the [Recommendation](https://github.com/chros73/rtorrent-ps_setup/wiki/Auto-Scraping#recommendation) section!

**Comment by colinhd8** [comment]
if without the scrape config:
for the complete torrent, will the rtorrent send announcement request to the tracker?
And will the tracker send peers list to rtorrent?

**Comment by chros73** [comment]
> for the complete torrent, will the rtorrent send announcement request to the tracker?

From the comment in config and wiki: "By default, rTorrent only sends scrape requests to trackers when a torrent is added for the first time or the client was restarted."
So: no.

> And will the tracker send peers list to rtorrent?

From the comment in config and wiki: "Retrieved information by scraping is only cosmetic using rTorrent (since it uses a different philosophy than most other torrent client, it won't affect the operation of it)"
So: yes. :)

**Comment by colinhd8** [comment]
Understand. Thank you.
