### ISSUE TITLE
Replace get_elapsed_time by convert.time_delta?

### ISSUE THREAD

**Issue by pyroscope** [chros73/rtorrent-ps_setup#148]
* 483d927 - convert.time_delta: indicate missing time vs. zero diff (#60) (2 weeks ago) <pyroscope>
* b9e32af - convert.time_delta: test for zero timestamp (2 weeks ago) <pyroscope>
* d7eaef8 - Rename convert.ui.elapsed_time to convert.time_delta, and add more tests (#60) (2 weeks ago) <pyroscope>

… and more commits.

**Comment by chros73** [comment]
Thanks, I'll take a look later.

**Comment by chros73** [comment]
Thanks, also fixed in: #150
