### ISSUE TITLE
Error in configuration Rtorrent.rc Line 10 / Rtorrent.rc.congi line 93

### ISSUE THREAD

**Issue by silveringking** [chros73/rtorrent-ps_setup#163]
So I tried to initiate rtorrent-ps-ch. I had previously installed rtorrent, rutorrent and auto-irissi and I was checking your scripts for automatic rotating of torrents. However while start rtorrent it gave me errors that do seem related with the download dirs.

`rtorrent: Error in option file: ~/.rtorrent.rc:10: Error in option file: ~/.rtorrent-config.rc:93: Invalid option name.

Could you help me out?

**Comment by chros73** [comment]
Line 93 is:
choke_group.up.heuristics.set 

Do you have the latest rtorrent-ps-ch compiled?

**Comment by silveringking** [comment]
@chros73  sorry for the late reply, while waiting for you answer I was focusing on something else. Anyway I was following your exact instruction as per the manual you wrote, so yeah I had the latest version compiled, unless the manual is outdated. I tried a second time, I was having a hard time setting up a password in the first steps, even when I imported the key, neither the key nor the password were accepted.

**Comment by chros73** [comment]
> unless the manual is outdated

It's updated.

> I was having a hard time setting up a password in the first steps, even when I imported the key, neither the key nor the password were accepted

Which step is this exactly? Can you link it?

**Comment by chros73** [comment]
Closed due to lack of info and probable user error. :)
