### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by wishbones** [chros73/rtorrent-ps_setup#164]
I hope it's ask some questions here. If not, let me know where is good :)

1) What is the `fullseed` group for?
2) What is the `load` group for?
3) Rotating is the `special` group aka the group using the default params?
4) Where would I add meta files for data I want to seed forever, with no rotation?

:D

**Comment by chros73** [comment]
> 1. What is the fullseed group for?
> 2. Rotating is the special group aka the group using the default params?
> 4. Where would I add meta files for data I want to seed forever, with no rotation?

It's [set up](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent-config.rc#L174) to have no upload limit restriction during seeding.
It's the same as `rotating` category, but the [queue manager](https://github.com/chros73/rtorrent-ps-ch_setup/wiki/Queue-Manager) can't delete downloads from `fullseed` category (that's the only difference.)

If you want to seed something forever without rotation:
- no upload speed limit: `fullseed` category
- with upload speed limits: any other category, except for: `rotating`, `unsafe`
- for [more info about moving downloads](https://github.com/chros73/rtorrent-ps-ch_setup/wiki/Additions#d-move-to-category-name-special-group-unsafe-data) when they are finished

[More info about groups](https://github.com/chros73/rtorrent-ps-ch_setup/wiki/Favoring-Group-Of-Torrents).

> 2. What is the load group for?

[This category](https://github.com/chros73/rtorrent-ps-ch_setup/blob/master/ubuntu-14.04/home/chros73/.rtorrent-config.rc#L184) can be used for downloads when you only one to select couple of files for downloading (not all of them):
- it only adds any download but it doesn't start leeching them, hence they doesn't occupy disk space.

**Comment by wishbones** [comment]
Got it. Thanks for the explanations.

It wasn't explicitly clear in my mind that there were 2 distinct concerns being addressed: rotation (disk space) and throttling (bw utilization).

Also finding this comment clarifies many things:
`#   'd.attribs.set' command receives 3 arguments: dirname,specialgroup,unsafe_data`

thanks again.
